name: Build Binaries

on:
  push:
    branches: [ steam-vent ]
  pull_request:
    branches: [ steam-vent ]
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    container:
      image: debian:12
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl build-essential git ca-certificates pkg-config libssl-dev
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          . $HOME/.cargo/env
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - name: Build
        run: RUSTFLAGS="-C link-arg=-Wl,-rpath,\$ORIGIN" cargo build --release --target x86_64-unknown-linux-gnu
      - name: Test
        run: cargo test --target x86_64-unknown-linux-gnu
      - name: Prepare artifact
        run: |
          mkdir -p artifact
          cp target/x86_64-unknown-linux-gnu/release/steam-auth artifact/
          find ~/.cargo/registry/src -path "*/steamworks-sys-*/lib/steam/redistributable_bin/linux64/libsteam_api.so" -exec cp {} artifact/ \;
      - uses: actions/upload-artifact@v4
        with:
          name: steam-auth-linux-x86_64
          path: artifact/*

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - name: Build
        run: cargo build --release --target x86_64-pc-windows-msvc
      - name: Test
        run: cargo test --target x86_64-pc-windows-msvc
      - name: Prepare artifact
        run: |
          mkdir artifact
          copy target\x86_64-pc-windows-msvc\release\steam-auth.exe artifact\
          Get-ChildItem -Path "$env:USERPROFILE\.cargo\registry\src" -Filter "steam_api64.dll" -Recurse | Where-Object { $_.FullName -like "*steamworks-sys-*\lib\steam\redistributable_bin\win64\*" } | ForEach-Object { Copy-Item $_.FullName "artifact\" }
      - uses: actions/upload-artifact@v4
        with:
          name: steam-auth-windows-x86_64.exe
          path: artifact/*
